<table width=100%>
<tr>
    <td><h1 style="text-align: left; font-size:300%;">
        NumPy - Hands On
    </h1></td>
    <td width="50%">
    <div style="text-align: right">
    <b> Practical Data Science Lessons</b><br><br>
    <b> Riccardo Bertoglio</b><br>
    <a href="mailto:riccardo.bertoglio@polimi.it">riccardo.bertoglio@polimi.it</a><br>
    </div>
</tr>
</table>

The following exercises are a selection from [this larger set.](https://github.com/rougier/numpy-100)

#### -> 1. Import the numpy package under the name `np` 

In [1]:
### YOUR CODE GOES HERE ###



#### 2. Create a vector of zeroes of size 10

In [2]:
### YOUR CODE GOES HERE ###



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a vector of zeroes of size 10 whose fifth value is 1

In [3]:
### YOUR CODE GOES HERE ###



[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### -> 4. Create a vector with values ranging from 10 to 49

In [4]:
### YOUR CODE GOES HERE ###



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### -> 5. Reverse the given 'Z' vector (first element becomes last)

In [5]:
Z = np.arange(50)

In [6]:
### YOUR CODE GOES HERE ###



[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 6. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
### YOUR CODE GOES HERE ###



[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### -> 7. Find indices of non-zero elements from [1,2,0,0,4,0] 
Note: Look for the `nonzero()` function in the documentation: https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html

In [8]:
### YOUR CODE GOES HERE ###



(array([0, 1, 4], dtype=int64),)


#### 8. Create a 3x3 identity matrix

In [9]:
### YOUR CODE GOES HERE ###



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 9. Create a 3x3x3 array with random values (sampled from a “continuous uniform” distribution)

In [10]:
### YOUR CODE GOES HERE ###



[[[0.45059526 0.08074638 0.06255285]
  [0.22266509 0.3656692  0.16084157]
  [0.18029007 0.14357548 0.07871257]]

 [[0.69530935 0.66198249 0.83583885]
  [0.04919942 0.96146067 0.04786715]
  [0.16127372 0.5417555  0.47235918]]

 [[0.72241346 0.04439576 0.42072192]
  [0.06935264 0.03137439 0.0180724 ]
  [0.0920472  0.61804877 0.0919691 ]]]


#### 10. Create a 10x10 array with random values and find the minimum and maximum values

In [11]:
### YOUR CODE GOES HERE ###



0.005624724780527113 0.9905854784119231


#### 11. Create a random vector of size 30 and find the mean value

In [12]:
### YOUR CODE GOES HERE ###



0.4981251889557534


#### -> 12. Create a 2D array with 1's on the border and 0's inside

In [ ]:
### YOUR CODE GOES HERE ###



#### 13. Add a border (filled with 0's) around the Z array
Note: look for the `pad()` Numpy function in the official documentation

In [14]:
Z = np.ones((5,5))

In [15]:
### YOUR CODE GOES HERE ###



[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### -> 14. Add a border (filled with 0's) inside the Z array
Note: use fancy indexing

In [16]:
Z = np.ones((5,5))

In [17]:
### YOUR CODE GOES HERE ###



[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 15. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Note: look for the `diag()` function

In [18]:
### YOUR CODE GOES HERE ###



[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Let's now create an array to work with

In [3]:
rng = np.random.default_rng(seed=16)
random_integers = rng.integers(low=1, high=500000, size=(20, 5))
random_integers

array([[351401, 100880, 203246,  95817, 437783],
       [424236,  84435,  33868, 342377, 437512],
       [ 53923,  33202, 252512,  43596,  35542],
       [332848, 404288, 294176, 445147, 203157],
       [172157, 478837, 383782, 182952, 251076],
       [111719, 121605,  21419, 488300, 118836],
       [244072, 323111, 401387, 278050, 413243],
       [349053,  16640, 449860, 238918, 119897],
       [ 91439, 433607, 116064,  93396, 448634],
       [409632, 371139, 364113, 116277, 281839],
       [392141, 257075, 143493,  51931, 150848],
       [392400, 161330, 407336, 423936,  60335],
       [170633, 356787, 196078, 111099, 392464],
       [161514, 471433, 420600, 222610, 492439],
       [250617,  31227, 206710, 429642, 288442],
       [ 22378, 295279, 464637, 315867,  18879],
       [ 35924, 458849, 497196, 439073, 261659],
       [480755,  23433, 284237, 239359, 400523],
       [437033, 161827, 300349, 296586, 350967],
       [ 14310,  29511, 449623,  80327, 221204]])

#### 16. Compute the average value of the second column

In [ ]:
### YOUR CODE GOES HERE ###


#### -> 17. Compute the average value for each of the first 5 rows considering only the third and fourth columns

In [ ]:
### YOUR CODE GOES HERE ###
